package gh.tpm.api.domain;

import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Getter;
import lombok.Setter;

/**
 * Identity shared by every table.
 *
 * <p>Ids are generated by Postgres via {@code gen_random_uuid()} rather than by
 * Hibernate, so a row written by a migration, a psql session or the application
 * all look the same. Equality is by id and is null-safe for unsaved instances.
 */
@MappedSuperclass
@Getter
@Setter
public abstract class BaseEntity {

    @Id
    @GeneratedValue
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof BaseEntity that) || !getClass().equals(other.getClass())) {
            return false;
        }
        // Two unsaved entities are only equal if they are the same instance,
        // which the identity check above already covered.
        return id != null && id.equals(that.id);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
